# Generated by Django 4.2.3 on 2023-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umobile_email', models.CharField(max_length=200)),
                ('ufull_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('upassword', models.CharField(max_length=200)),
                ('uphoto', models.ImageField(upload_to='static/uploaded/profile_potos/')),
                ('ubio', models.CharField(max_length=200)),
                ('ugender', models.CharField(max_length=200)),
                ('uwebsite', models.CharField(max_length=200)),
                ('ufollowers',models.IntegerField()),
                ('ufollowings',models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterUserModel',
        ),
    ]
