# Generated by Django 4.2.3 on 2023-08-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0003_alter_userdetailsmodel_uphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsmodel',
            name='uphoto',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
