# Generated by Django 4.2.3 on 2023-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0005_alter_userdetailsmodel_uphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='postModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upost', models.ImageField(upload_to='static/uploaded/posts')),
            ],
        ),
    ]
