# Generated by Django 4.2.3 on 2023-08-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0007_postdetailsmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='allPostModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_photo', models.ImageField(upload_to='static/uploaded/posts')),
                ('post_caption', models.CharField(max_length=200)),
                ('post_location', models.CharField(max_length=200)),
                ('post_tag', models.CharField(max_length=200)),
                ('post_time', models.CharField(max_length=200)),
                ('post_comment', models.IntegerField()),
                ('post_likes', models.IntegerField()),
                ('post_user_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.userdetailsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='postDetailsModal',
        ),
    ]
