# Generated by Django 4.2.3 on 2023-08-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0008_allpostmodal_delete_postdetailsmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='allComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pComment', models.CharField(max_length=255)),
                ('post_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.allpostmodal')),
                ('comment_time', models.CharField(max_length=200)),
                ('comment_likes', models.IntegerField()),
                ('who_comment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.UserDetailsModel')),

            ],
        ),
    ]
