# Generated by Django 4.2.3 on 2023-08-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0009_allcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allComment',
            new_name='allCommentModal',
        ),
    ]
