# Generated by Django 4.2.3 on 2023-08-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0010_rename_allcomment_allcommentmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.allpostmodal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.userdetailsmodel')),
            ],
        ),
    ]
