# Generated by Django 4.2.3 on 2023-08-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0011_userlikepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcommentmodal',
            name='who_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.userdetailsmodel'),
        ),
    ]
