# Generated by Django 4.2.3 on 2023-08-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0012_alter_allcommentmodal_who_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='allCommenDetailstModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pComment', models.CharField(max_length=255)),
                ('comment_time', models.CharField(max_length=200)),
                ('comment_likes', models.IntegerField()),
                ('post_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.allpostmodal')),
                ('who_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.userdetailsmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='allCommentModal',
        ),
    ]
