# Generated by Django 4.2.3 on 2023-08-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagramApp', '0013_allcommendetailstmodal_delete_allcommentmodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user_id', models.IntegerField()),
                ('follow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagramApp.userdetailsmodel')),
            ],
        ),
    ]
